/**
 * Project Jano - User microservice
 * This is the API of Project Jano
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ezequiel.aceto+project-jano@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.jano.mobile.libs.android.models

import android.content.Context
import android.webkit.WebSettings
import io.jano.mobile.libs.android.security.Constants

/**
 * A simple representation of the current device.
 * @param platform Platform of the device where the certificate was created. Value is 'mobile' for Android SDK
 * @param userAgent User agent of the device where the certificate was generated
 */
data class Device private constructor(
    internal val platform: String,
    internal val userAgent: String
) {
    companion object {
        internal fun fromLocalDevice(context: Context): Device {
            return Device(
                platform = Constants.PLATFORM,
                userAgent = WebSettings.getDefaultUserAgent(context)
            )
        }
    }
}