name: Build documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Setup JDK v11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Remove old documentation
        run: |
          rm -rf docs/github
          mkdir -p docs/github

      - name: Build documentation
        run: ./gradlew clean dokkaGfm dokkaHtml dokkaJavadoc

      - name: Commit documentation files
        run: |
          echo "Document updated: $(date '+%d %b %Y %H:%M:%S')" > UPDATED.md
          git config --local user.email "project.jano+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update documentation"

      - name: Push changes in documentation
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true